# define Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: username-namespace

---

# define ResourceQuota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: username-quota
  namespace: username-namespace
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "10"
