apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.serviceAccount.name }}-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}